/*
 * CSCE 247
 * October 28, 2022
 * Activity.
 * Represents an available activity for the camp.
 */
public enum Activity{
    WAKEUP__CABIN,
    BREAKFAST__CABIN,
    LUNCH__CABIN,
    DINNER__CABIN,
    SLEEP__CABIN,
    ARCHERY__FIELD,
    PUMPKIN__FIELD,
    SWIMMING__POOL,
    WALKING__TRACK,
    RUNNING__TRACK,
    JOGGING__TRACK,
    JUMPING__FIELD,
    ROPES__FUN_ZONE,
    FRIENDLY_CONVERSATION__CABIN,
    LIFE_ADVICE__CABIN,
    PHILOSOPHICAL_DISCUSSION__LIBRARY,
    TAXES__LIBRARY,
    GROCERIES__MARKET,
    DISHES__CABIN,
    LAUNDRY__CABIN,
    GAMES__CABIN,
    ARTS__CABIN,
    CRAFTS__CABIN,
    SANTA__CABIN,
    VALENTINES__CABIN,
    SLIP_N_SLIDE__CABIN,
    EAT_CANDY__CABIN,
    THROW_STICKS__FIELD,
    SUPER_HAPPY__EVERYWHERE
}